<div style="background:#222222; color:#ffffff; padding:20px">
<h1 align="center">Guided ML With The Iris Dataset</h1>

<h2 align="center" tyle="color:#01ff84" >Learning type | Activity type | Objective |</h2>
<h2 align="center">| Supervised | Multiclass classification | Identify a flower's class |</h2>


<div>

Contents:

1. Loading the data
2. Setting up supervised learning problem (selecting features)
3. Creating a first model
    - Creating train and test datasets
    - Normalizing train and test
    - Fitting and predicting
4. Evaluate the frist model predictions
5. Crossvalidation of the model
6. Creating an end to end ML pipeline
    - Train/Test Split
    - Normalize
    - Crossvalidations
    - Model
    - fitting and predicting

## Instructions with NBGrader removed

Complete the cells beginning with `# YOUR CODE HERE` and run the subsequent cells to check your code.


Contents:
1. Loading the data
2. Setting up supervised learning problem (selecting features)
3. Creating a first model
    - Creating train and test datasets
    - Normalizing train and test
    - Fitting and predicting
4. Evaluate the frist model predictions
5. Crossvalidation of the model
6. Creating an end to end ML pipeline
    - Train/Test Split
    - Normalize
    - Crossvalidations
    - Model
    - fitting and predicting

## About the dataset

[Iris](https://archive.ics.uci.edu/ml/datasets/iris) is a well-known multiclass dataset. It contains 3 classes of flowers with 50 examples each. There are a total of 4 features for each flower.

![](./classic-datasets/images/Iris-versicolor-21_1.jpg)

## Package setups

1. Run the following two cells to initalize the required libraries. 

In [88]:
#to debug package errors
import sys
sys.path
sys.executable

'C:\\Users\\bilal\\Anaconda3\\python.exe'

In [89]:
# Import needed packages
# You may add or remove packages should you need them
import numpy as np
import matplotlib
import matplotlib.pyplot as plt
import seaborn as sns
import pandas as pd
from sklearn import datasets
from sklearn import model_selection
from sklearn.preprocessing import StandardScaler
from sklearn import preprocessing
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split, cross_validate
from sklearn.pipeline import make_pipeline

# Display plots inline and change plot resolution to retina
%matplotlib inline
%config InlineBackend.figure_format = 'retina'
# Set Seaborn aesthetic parameters to defaults
sns.set()

## Step 1: Loading the data

1. Load the iris dataset using ```datasets.load_iris()```
2. Investigate the data structure with ```.keys()```
3. Construct a dataframe from the dataset
4. Create a 'target' and a 'class' column that contains the target names and values
5. Display a random sample of the dataframe 

In [90]:
def load_data():
    iris_data = datasets.load_iris()
    return iris_data

In [91]:
assert load_data()['data'].shape == (150,4)

In [92]:
dataset = load_data()
print(load_data().feature_names)
dataset.keys()

['sepal length (cm)', 'sepal width (cm)', 'petal length (cm)', 'petal width (cm)']


dict_keys(['data', 'target', 'frame', 'target_names', 'DESCR', 'feature_names', 'filename'])

In [93]:
def dataset_to_pandas():
    df = pd.DataFrame(dataset["data"], columns=dataset.feature_names)
    df.columns = ["sepal length", "sepal width", "petal length", "petal width"]
    df["target"] = dataset.target
    # Gets list of the target_names in the dataset
    target_names = dataset.target_names
    # print(target_names)
    # Creates new series in dataframe and replaces the values in the series to the target names depending
    # on the target number in the column target, using a dictionary.
    df['class'] = df['target'].replace({0: target_names[0], 1: target_names[1], 2: target_names[2]})
    return df

In [94]:
df = dataset_to_pandas()
assert df['sepal length'].shape == (150,)
assert df['sepal width'].shape == (150,)
assert df['petal length'].shape == (150,)
assert df['petal width'].shape == (150,)
assert df['target'].shape == (150,)
assert df['class'].shape == (150,)

df.head()

sepal length  sepal width  petal length  petal width  target   class
0           5.1          3.5           1.4          0.2       0  setosa
1           4.9          3.0           1.4          0.2       0  setosa
2           4.7          3.2           1.3          0.2       0  setosa
3           4.6          3.1           1.5          0.2       0  setosa
4           5.0          3.6           1.4          0.2       0  setosa

### Question
Find the X and y values we're looking for. Notice that y is categorical and thus, we could **one-hot encode it** if we are looking at **class** or we can just pick **target**. In order to one hot encode we have  to re-shape `y` it using the **.get_dummies** function. 

## For the purpose of this exercise, do not use hot encoding, go only for target but think about if you have to drop it somewhere or not...

In [95]:
df_iris = dataset_to_pandas()
df_iris

sepal length  sepal width  petal length  petal width  target      class
0             5.1          3.5           1.4          0.2       0     setosa
1             4.9          3.0           1.4          0.2       0     setosa
2             4.7          3.2           1.3          0.2       0     setosa
3             4.6          3.1           1.5          0.2       0     setosa
4             5.0          3.6           1.4          0.2       0     setosa
..            ...          ...           ...          ...     ...        ...
145           6.7          3.0           5.2          2.3       2  virginica
146           6.3          2.5           5.0          1.9       2  virginica
147           6.5          3.0           5.2          2.0       2  virginica
148           6.2          3.4           5.4          2.3       2  virginica
149           5.9          3.0           5.1          1.8       2  virginica

[150 rows x 6 columns]

In [96]:
def ohe():
    return pd.get_dummies(df_iris, columns=["target"])
ohe()

sepal length  sepal width  petal length  petal width      class  \
0             5.1          3.5           1.4          0.2     setosa   
1             4.9          3.0           1.4          0.2     setosa   
2             4.7          3.2           1.3          0.2     setosa   
3             4.6          3.1           1.5          0.2     setosa   
4             5.0          3.6           1.4          0.2     setosa   
..            ...          ...           ...          ...        ...   
145           6.7          3.0           5.2          2.3  virginica   
146           6.3          2.5           5.0          1.9  virginica   
147           6.5          3.0           5.2          2.0  virginica   
148           6.2          3.4           5.4          2.3  virginica   
149           5.9          3.0           5.1          1.8  virginica   

     target_0  target_1  target_2  
0           1         0         0  
1           1         0         0  
2           1         0         0  
3           1         0         0  
4           1         0         0  
..        ...       ...       ...  
145         0         0         1  
146         0         0         1  
147         0         0         1  
148         0         0         1  
149         0         0         1  

[150 rows x 8 columns]

In [97]:
ohe_data = ohe()

assert ohe_data.shape == (150,8)

## Step 2: Setting up supervised learning problem (selecting features)

Feature selection is an essential step in improving a model's perfromance. In the first version of the model we will use the **'sepal length'** and **'sepal width'** as predicting features. Later we will see the effect of adding additional features.

1. Assign the values of the 'target' to Y as a numpy array
2. Assign the remaining feature values to X as a numpy array
3. Check the shape of X and Y. Check the first few values.
    - Can we confirm our X and Y are created correctly?

In [98]:
def target_to_numpy():
    y=df_iris.target.to_numpy()
    return y
def data_to_numpy():
    x = df_iris[["sepal length", "sepal width"]].to_numpy()
    return x

In [99]:
Y = target_to_numpy()
X = data_to_numpy()
assert isinstance(Y, np.ndarray)
assert isinstance(X, np.ndarray)
assert X.shape == (150,2)

In [100]:
X = df_iris[['sepal length', 'sepal width']].values
print(f"The shape of X is {X.shape} and its first 5 values are \n{X[:5]}\n")
print(f"The shape of Y is {Y.shape} and its first 5 values are \n{Y[:5]}\n")

The shape of X is (150, 2) and its first 5 values are 
[[5.1 3.5]
 [4.9 3. ]
 [4.7 3.2]
 [4.6 3.1]
 [5.  3.6]]

The shape of Y is (150,) and its first 5 values are 
[0 0 0 0 0]



## Step 3: Creating the first model

In lecture we learned about creating a train and test datasets, normalizing, and fitting a model. In this step we will see how to build a simple version of this.

We have to be careful when constructing our train and test datasets. First, when we create train and test datasets we have to be careful that we always have the same datapoints in each set. Otherwise our results won't be reproduceable or we might introduce a bias into our model.

We also need to be attentive to when we normalize the data. What would be the effect of normalizing the data (i.e. with StandardScaler to a range between 0 - 1) before we create our train and test sets? Effectively we would use information in the test set to structure the values in the training set and vice versa. Therefore normalizing train and test independently is the preferred method.

1. Create X_train, X_test, Y_train, Y_test using ```train_test_split()``` with an 80/20 train/test split. Look in the SKLearn documentation to understand how the function works.
    - Inspect the first few rows of X_train.
    - Run the cell a few times. Do the first few rows change?
    - What option can we use in ```train_test_split()``` to stop this from happening?
2. Normalize the train and test datasets with ```StandardScaler```
    - We can fit the transform with ```.fit()``` and ```.transform()``` to apply it. Look in the documentation for an example of how to do this.
    - Does it make sense to normalize Y_train and Y_test?
3. Initalize a ```LogisticRegression()``` model and use the ```.fit()``` method to initalize the first model.
    - We will pass the X_train and Y_train variables to the ```.fit()``` method.
    - Once the model is fit, use the ```.predict()``` with the X_test and save the output as predictions.

In [101]:
#split train and test data 80/20

# X_train & X_test are both the Features that we chose but split up 80/20 respectively for training and testing group
# Y_train & Y_test are both the prediction targets, the data we are trying to predict, but split up 80/20 respectively for training and testing group

#X_train and Y_train are used for training the model. i.e. its the training data.
#X_test and Y_test are used for validating the model. i.e. its the validation data.

#random_state argument used to ensure same values are given to train and test datasets

X_train, X_test, Y_train, Y_test = train_test_split(X, Y, train_size=0.8, random_state=42)


print(X_train[:5])

print(X_train.shape)
print(Y_train.shape)
print(X_test.shape)
print(Y_test.shape)

[[4.6 3.6]
 [5.7 4.4]
 [6.7 3.1]
 [4.8 3.4]
 [4.4 3.2]]
(120, 2)
(120,)
(30, 2)
(30,)


In [102]:
assert X_train.shape == (120,2)
assert Y_train.shape == (120,)
assert X_test.shape  == (30,2)
assert Y_test.shape  == (30,)

In [103]:
#normalize the dataset
#Normalization is the process of adjusting values measured on different scales to a common scale.

#By setting copy to false, it does inplace scaling,replaces the data in the array with the normalized data,
# but only tends to work for numpy arrays.
scaler = StandardScaler(copy=False)

#create and fit the scaler object on the training data

#Fit method computes the mean and standard deviation of each of the features in the data given of our training data.
scaler.fit(X_train)

#Then the transform method performs standardization by centering and scaling(uses the mean and std)
scaler.transform(X_train)
scaler.transform(X_test)

#We fit our StandardScaler object first using our training group and then transform our test group using that same object.
#We normalize this way because we use our data to train our model, so we would want the standardscaler object to register
#and proceed with the mean and std of out training set and transform the test group using it. otherwise we would be doing
#2 different transformations, taking 2 different means and 2 different std, treating as different data that's supposed
#to be the same.

#We would not normalize Y_train and Y_test as this is our prediction target, it is what we are trying to predict as such,
# normalizing would not make any sense as we're not calculating anything with it.



array([[ 0.35451684, -0.58505976],
       [-0.13307079,  1.65083742],
       [ 2.30486738, -1.0322392 ],
       [ 0.23261993, -0.36147005],
       [ 1.2077952 , -0.58505976],
       [-0.49876152,  0.75647855],
       [-0.2549677 , -0.36147005],
       [ 1.32969211,  0.08570939],
       [ 0.47641375, -1.92659808],
       [-0.01117388, -0.80864948],
       [ 0.84210448,  0.30929911],
       [-1.23014297, -0.13788033],
       [-0.37686461,  0.98006827],
       [-1.10824606,  0.08570939],
       [-0.86445224,  1.65083742],
       [ 0.59831066,  0.53288883],
       [ 0.84210448, -0.13788033],
       [-0.2549677 , -1.25582892],
       [-0.13307079, -0.58505976],
       [ 0.72020757, -0.58505976],
       [-1.35203988,  0.30929911],
       [ 0.35451684, -0.13788033],
       [-0.98634915,  0.75647855],
       [ 0.72020757, -0.58505976],
       [ 2.5486612 ,  1.65083742],
       [ 1.08589829, -0.13788033],
       [ 1.08589829, -1.25582892],
       [ 1.2077952 ,  0.30929911],
       [-1.23014297,

In [104]:
assert np.amin(X_train) >= -2.5
assert np.amax(X_train) <= 3.2
assert np.amin(X_test) >= -2
assert np.amin(X_test) <= 2.75

In [105]:
#initalize and fit with Logistic Regression
prediction = 0
#Defining Model
lr_model = LogisticRegression(random_state=10)

#Fitting the model
lr_model.fit(X_train, Y_train)

#initalize the logistic regressor
#make predictions
predictions = lr_model.predict(X_test)
print(predictions)

[1 0 2 1 2 0 1 2 1 1 2 0 0 0 0 2 2 1 1 2 0 1 0 2 2 2 2 2 0 0]


In [106]:
assert predictions.shape == (30,)

## Step 4: Evaluate the frist model's predictions

We will learn more about how to evaluate the performance of a classifier in later lessons. For now we will use % accuracy as our metric. It is important to know that this metric only helps us understand the specific performance of our model and not, for example, where we can improve it, or where it already perfoms well.

1. Use ```.score()``` to evaluate the performance of our first model.

In [107]:
score = 0
#evaluating the performance of our first model

score = lr_model.score(X_test, Y_test)
print(f"The performance of our model is {score}. i.e. it is {score*100}% accurate")


The performance of our model is 0.9. i.e. it is 90.0% accurate


In [108]:
assert score >=0.7

In [109]:
assert score >=0.72

In [110]:
assert score >=0.73

## Step 5: Crossvalidation of the model
Our first model achived ~90% accruacy. This is quite good. How do we know it is reproducable? If we run the model again and our performance is 85% which is correct? And what about improving our model? Can you think of one thing we can do to potentially improve the model?

#### Crossvalidation
Corssvalidation is when we create multiple X and Y datasets. On each dataset we train and fit the model. We then average the results and return a 'crossvalidated' accruacy.

1. Initalize a new version of the model you trained above with the same paramters.
2. Use ```cross_validate()``` to run the model with 5 crossvalidation folds. 

In [111]:
#model with cross validation
lr_model = LogisticRegression(random_state=10).fit(X_train, Y_train)

#cross validate the training set
clf_cv = 0
CV = 0
cv = cross_validate(lr_model, X_train, Y_train)
print(cv.keys())

def print_scores(cv):
    #print out cross validation scores
    [print('Crossvalidation fold: {}  Accruacy: {}'.format(n, score)) for n, score in enumerate(cv['test_score'])]
    #print out the mean of the cross validation
    print('Mean train cross validation score {}'.format(cv['test_score'].mean()))
    
print_scores(cv)

dict_keys(['fit_time', 'score_time', 'test_score'])
Crossvalidation fold: 0  Accruacy: 0.7083333333333334
Crossvalidation fold: 1  Accruacy: 0.75
Crossvalidation fold: 2  Accruacy: 0.875
Crossvalidation fold: 3  Accruacy: 0.8333333333333334
Crossvalidation fold: 4  Accruacy: 0.75
Mean train cross validation score 0.7833333333333334


In [114]:
assert len(cv['test_score']) == 5
assert max(cv['test_score']) >= 0.85
assert min(cv['test_score']) >= 0.69
assert cv['test_score'].mean() >= 0.77

## Step 6: Creating an end to end ML pipeline
Congraulations you've trained, crossvalidated, predicted, and evaluated your frist classifier. Now that you understand the basic steps we will look at a way to combine all these steps together.

Before we go further think about what you would have to do if you wanted to change the model. Intalize a new model, change the vairables, redo the cross validation...etc. Seems like a lot. And when we have to change lots of code it is easy to make mistakes. And what if you wanted to try many models and see which one performed best? Or try changing many different features? How could you do it without writing each one out as we have?

The solution is to use SKLearn's pipeline class. A pipeline is an object that will execute the various steps in the machine learning process. We can choose what elements we want in the pipeline and those that we do not. Once setup, we can rapidly change models, or input data and have it return our results in an ordered way.


1. Initalize a scaler and a classifer object like we did previously.
2. Use the ```make_pipeline()``` function to construct a transofmraiton pipeline for the scaler and the classifier
3. Input the pipeline object to the cross_validator and evaluate with 5 folds.
4. Print out your results (hint: make a function for repetitve tasks like printing)

In [113]:
#define the scaler
#define the classifier
#make the pipeline
#run the cross validation
#print results
scaler = 0
classifier = 0
pipe = 0
scores = 0
# YOUR CODE HERE
raise NotImplementedError()


NotImplementedError: 

In [ ]:
assert type(pipe) == type(make_pipeline(scaler, classifier))
assert len(cv['test_score']) == 5
assert max(cv['test_score']) >= 0.83
assert min(cv['test_score']) >= 0.69
assert cv['test_score'].mean() >= 0.74

## Challenge Exercise

In this notebook we only used two features to predict the class of the flower. We also did not do any hypter parameter tuning. The challenge is to impove the prediction results. Some ideas we can try:
1. Add features to the input and run the cross validation pipeline
2. Investigate how to use ```GridSearchCV```, a powerful funtion that searches through hyperparmetrs and does cross validation.
    - Hint: Input the pipeline directly into GridSearchCV
3. Try a different models like RandomForest or SVM.

In [ ]:
# YOUR CODE HERE
raise NotImplementedError()

In [ ]:
# YOUR CODE HERE
raise NotImplementedError()

In [ ]:
# YOUR CODE HERE
raise NotImplementedError()

In [ ]:
# YOUR CODE HERE
raise NotImplementedError()

In [ ]:
# YOUR CODE HERE
raise NotImplementedError()